### ISSUE TITLE
Validation videos availablility

### ISSUE THREAD

**Issue by vandana-rajan** [pengsongyou/OMGEmoChallenge-ADSC#2]
Hi,

Thanks a lot for sharing the code.

When I downloaded the validation videos, I found that a number of them are 'unavailable'. Could you please tell how many were available for you? 

Thanks,

**Comment by pengsongyou** [comment]
Hi,

It was a project from long time ago, so I don't really remember the number, but I guess it was probably less than 20? However, since the videos are directly from some links on Youtube as far as I remember, so I guess over the years, more and more videos might be invalid already. Hope this could help a little bit.

Thanks!

**Comment by vandana-rajan** [comment]
Thanks a lot for the quick reply and the info.
